aa: null
amp: true
apex_amp: false
aug_splits: 0
batch_size: 128
bn_eps: null
bn_momentum: null
bn_tf: false
channels_last: false
checkpoint_hist: 5
clip_grad: null
clip_mode: norm
color_jitter: 0.4
cooldown_epochs: 0
crop_pct: null
cutmix: 0.0
cutmix_minmax: null
data_dir: /disk2/datasets/imagenet
dataset: ''
decay_epochs: 30
decay_rate: 0.1
dist_bn: ''
drop: 0.2
drop_block: null
drop_connect: null
drop_path: null
epoch_repeats: 0.0
epochs: 300
eval_metric: top1
experiment: ''
gp: null
hflip: 0.5
img_size: null
initial_checkpoint: ''
input_size: null
interpolation: ''
jsd: false
local_rank: 0
log_interval: 50
log_wandb: false
lr: 0.6
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean: null
min_lr: 1.0e-05
mixup: 0.0
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: repghost.repghostnet_1_11x
model_ema: true
model_ema_decay: 0.9999
model_ema_force_cpu: false
momentum: 0.9
native_amp: false
no_aug: false
no_prefetcher: false
no_resume_opt: false
num_classes: 1000
opt: sgd
opt_betas: null
opt_eps: null
output: work_dirs/train/
patience_epochs: 10
pin_mem: false
pretrained: false
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.2
resplit: false
resume: ''
save_images: false
scale:
- 0.08
- 1.0
sched: cosine
seed: 42
smoothing: 0.1
split_bn: false
start_epoch: null
std: null
sync_bn: false
torchscript: false
train_interpolation: random
train_split: train
tta: 0
use_multi_epochs_loader: false
val_split: val
validation_batch_size_multiplier: 1
vflip: 0.0
warmup_epochs: 5
warmup_lr: 0.0001
weight_decay: 1.0e-05
workers: 7
